-- MySQL Script generated by MySQL Workbench
-- Mon Nov 18 02:46:29 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sistemadeestoque
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistemadeestoque
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistemadeestoque` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `sistemadeestoque` ;

-- -----------------------------------------------------
-- Table `sistemadeestoque`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemadeestoque`.`usuarios` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(150) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `tipo_usuario` TINYINT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `idUsuario_UNIQUE` (`idUsuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemadeestoque`.`setores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemadeestoque`.`setores` (
  `idSetor` INT NOT NULL AUTO_INCREMENT,
  `setor` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idSetor`),
  UNIQUE INDEX `idSetor_UNIQUE` (`idSetor` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemadeestoque`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemadeestoque`.`produtos` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `preço_compra` FLOAT(10,2) NOT NULL,
  `preço_venda` FLOAT(10,2) NOT NULL,
  `estoque` INT NOT NULL,
  `distribuidora` VARCHAR(255) NOT NULL,
  `idSetor` INT NOT NULL,
  PRIMARY KEY (`idProduto`, `idSetor`),
  UNIQUE INDEX `idProduto_UNIQUE` (`idProduto` ASC) VISIBLE,
  INDEX `fk_produtos_setores_idx` (`idSetor` ASC) VISIBLE,
  CONSTRAINT `fk_produtos_setores`
    FOREIGN KEY (`idSetor`)
    REFERENCES `sistemadeestoque`.`setores` (`idSetor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
